SBP add shopping cart model
petro2061/online-book-store-project pull request #10
Opened 2024-07-29 22:07 UTC by petro2061

In this task added new controller for management shopping cart for the currently authorized user. Also adden model that representet product in shopping cart. Added required Dto classes, repository layer with custom methods and servise layer with the necessary methods. That methods helps add new product (in our case book) to shopping cart, update data about product and delete product from shoppind cart. This methods use in controller layer.

2024-07-30 12:26 UTC, Elena-Bruyako requested changes
see comments

2024-07-30 12:26 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/controller/ShoppingCartController.java
> +    public CartItemDto addCartItemToShoppingCart(
```suggestion
    public ShoppingCartDto addCartItemToShoppingCart(
```

2024-07-30 12:26 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/controller/ShoppingCartController.java
> +    public CartItemDto updateCartItemInShoppingCart(
```suggestion
    public ShoppingCartDto updateCartItemInShoppingCart(
```

2024-07-30 12:26 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/controller/ShoppingCartController.java
> +    public CartItemDto removeCartItemFromShoppingCart(
```suggestion
    public void removeCartItemFromShoppingCart(
```

2024-07-30 12:26 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/dto/cartitem/CreateCartItemRequestDto.java
> +        @NotNull (message = "Field bookId can't be null")
```suggestion
        @NotNull(message = "Field bookId can't be null")
        @Positive(
```

2024-07-30 12:26 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/dto/cartitem/CreateCartItemRequestDto.java
> +        @Min(value = 1, message = "Quantity can't be less one")
It's better to use `@Positive`

2024-07-30 12:26 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/dto/cartitem/CreateCartItemUpdateRequestDto.java
> +        @Min(value = 1, message = "Quantity can't be less one")
`@Positive`

2024-07-30 12:26 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/service/shopingcart/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCar = getShoppingCartForUser(userId);
```suggestion
        return shoppingCartMapper.toDto(shoppingCartRepository.findByUserId(userId));
```

2024-07-30 12:26 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/service/shopingcart/impl/ShoppingCartServiceImpl.java
> +    @Transactional
```suggestion
```

2024-07-30 12:26 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/service/shopingcart/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCar = getShoppingCartForUser(userId);
```suggestion
        ShoppingCart shoppingCart = getShoppingCartForUser(userId);
```

2024-07-30 12:26 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/service/shopingcart/impl/ShoppingCartServiceImpl.java
> +        CartItem cartItem = getCartItemById(cartItemId);
Or 
```suggestion
        CartItem cartItem = cartItemRepository.findByIdAndShoppingCartId(cartItemId, cart.getId())
                .map(item -> {
                    item.setQuantity(itemDto.quantity());
                    return item;
                }).orElseThrow(() -> new EntityNotFoundException(
                        String.format("No cart item with id: %d for user: %d", cartItemId, userId)
                ));
```

2024-07-30 12:26 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/service/user/impl/UserServiceImpl.java
> +        ShoppingCart shoppingCart = new ShoppingCart();
create method `createShoppingCart` in ShopCartService for these logic

2024-08-02 08:49 UTC, petro2061 commented
Changed the implementation of methods at the service level. Fixed code style issues. Added new methods to service layer and storage layer.

2024-08-02 17:17 UTC, okuzan requested changes

2024-08-02 17:17 UTC, okuzan commented on src/main/java/project/onlinebookstore/controller/ShoppingCartController.java
> +        User user = (User) authentication.getPrincipal();
extract repeated logic to a private method

2024-08-02 17:17 UTC, okuzan commented on src/main/java/project/onlinebookstore/dto/cartitem/CreateCartItemRequestDto.java
> +        @NotNull(message = "Field bookId can't be null")
You can use Positive here too

2024-08-02 17:17 UTC, okuzan commented on src/main/java/project/onlinebookstore/model/ShoppingCart.java
> +@SQLRestriction(value = "is_deleted = false")
```suggestion
@SQLDelete(sql = "UPDATE shopping_carts SET is_deleted = TRUE WHERE id =?")
@SQLRestriction(value = "is_deleted = FALSE")
```

2024-08-02 17:17 UTC, okuzan commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/10-create-cart-items-table.yaml
```suggestion
      file: db/changelog/changes/10-create-cart-items-table.yaml

```

2024-08-02 17:17 UTC, okuzan commented on src/main/resources/db/changelog/changes/10-create-cart-items-table.yaml
> +            referencedTableName: books
```suggestion
            referencedTableName: books

```
![image](https://github.com/user-attachments/assets/f695b9bf-0b08-41bf-bfae-418bbf121571)
always review your PR, if you see this red sign, it means you need to add one more empty line

2024-08-02 17:17 UTC, okuzan commented on src/main/java/project/onlinebookstore/service/shopingcart/impl/ShoppingCartServiceImpl.java
> +    public void createShoppingCart(User user) {
Add Override

2024-08-03 09:03 UTC, petro2061 commented
Added new private method to ShoppingCart Controller. Fixsed problem with codestyle.

2024-08-04 16:00 UTC, Elena-Bruyako requested changes
see comments

2024-08-04 16:00 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/controller/ShoppingCartController.java
> +    private User getAuthenticationUser(Authentication authentication) {
```suggestion
    private Long getAuthenticationUser(Authentication authentication) {
```

return Long userId

2024-08-04 16:00 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/dto/cartitem/CreateCartItemRequestDto.java
> +        @Positive(message = "Field bookId can't be null")
```suggestion
        @Positive(message = "Field bookId can't be null")
        @NotNull
```

"Field bookId can't be null" wrong message for that annotation

2024-08-04 16:00 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/service/shopingcart/impl/ShoppingCartServiceImpl.java
> +        Book book = bookRepository.findById(cartItemRequestDto.bookId())
replace before  cartItemRepository.findByShoppingCartIdAndBookId to check if Book exists in DB, if not you don't call that method

2024-08-04 21:10 UTC, petro2061 commented
The method call order has been changed in addCartItemToShoppingCart in ShoppingCartServiceImpl class. Also chenged return type in private method in ShoppingCartController.

2024-08-06 10:55 UTC, MentorMateAcademy requested changes

2024-08-06 10:55 UTC, MentorMateAcademy commented on src/main/java/project/onlinebookstore/repository/cartitem/CartItemRepository.java
> +@Repository
```suggestion
```

2024-08-06 10:55 UTC, MentorMateAcademy commented on src/main/java/project/onlinebookstore/repository/cartitem/CartItemRepository.java
> +@Repository
this anno redundant

2024-08-06 15:45 UTC, petro2061 commented
Deleted redundant annotation.

2024-08-07 17:10 UTC, sarakhmen approved these changes

2024-08-07 21:01 UTC, merged