SBP add order model
petro2061/online-book-store-project pull request #11
Opened 2024-08-12 10:00 UTC by petro2061

In this task added new functional for managements users orders. Added new controller class with endpoints for create, update and get order and order items for user. As user you can get all orders, create order from your shopping cart and get items from your order. As admin you can changed order status.

2024-08-12 12:48 UTC, Elena-Bruyako requested changes
see comments

2024-08-12 12:48 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/controller/OrderController.java
> +            @Parameter(description = "Represents the customer's shipping address")
wrong description

2024-08-12 12:48 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/controller/OrderController.java
> +    private Long getAuthenticationUserByUserId(Authentication authentication) {
wrong name of method, you don't get user

2024-08-12 12:48 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/dto/order/CreateOrderRequestDto.java
> +        @NotBlank(message = "Sipping address can't be null")
```suggestion
        @NotBlank(message = "Shipping address can't be null")
```

2024-08-12 12:48 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/dto/order/CreateOrderUpdateRequestDto.java
> +        Order.Status status
```suggestion
        @NotNull(message = "Status cannot be null")
        Order.Status status
```

2024-08-12 12:48 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/service/order/OrderService.java
> +    List<OrderDto> getAllOrder(Long userId, Pageable pageable);
```suggestion
    List<OrderDto> getAllOrders(Long userId, Pageable pageable);
```

2024-08-12 12:48 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/service/order/impl/OrderServiceImpl.java
> +        Order savedOrder = orderRepository.save(order);
```suggestion
        orderRepository.save(order);
```

2024-08-12 12:48 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/service/order/impl/OrderServiceImpl.java
> +        return orderMapper.toDto(savedOrder);
```suggestion
        return orderMapper.toDto(order);
```

2024-08-12 12:48 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/service/order/impl/OrderServiceImpl.java
> +        List<Order> byUserIdWithItems
rename variable

2024-08-14 08:10 UTC, petro2061 commented
Corrected mentor's comments on code style

2024-08-14 12:14 UTC, Elena-Bruyako requested changes
left some comments

2024-08-14 12:14 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/service/order/impl/OrderServiceImpl.java
> +        List<Order> byUserId
rename please

2024-08-14 12:14 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/service/order/impl/OrderServiceImpl.java
> +
```suggestion
```

2024-08-15 06:07 UTC, petro2061 commented
Renamed variable in  getAllOrders method

2024-08-15 10:28 UTC, Elena-Bruyako approved these changes

2024-08-17 06:47 UTC, merged