Add docker
petro2061/online-book-store-project pull request #12
Opened 2024-08-17 06:49 UTC by petro2061

Added docker to project

2024-08-19 18:41 UTC, sarakhmen approved these changes
good job!

2024-08-19 19:15 UTC, sarakhmen approved these changes

2024-08-20 16:18 UTC, okuzan requested changes
remove .env - git rm --cached .env
add to gitignore
add .env.template with actual values removed

2024-08-20 17:38 UTC, petro2061 commented
Deleted .env file from git checking and add to gitignore file.

2024-08-21 11:05 UTC, okuzan approved these changes

2024-08-27 17:02 UTC, merged