Add tests
petro2061/online-book-store-project pull request #14
Opened 2024-09-09 20:32 UTC by petro2061

This task added classes to test the services, repositories, and controllers for the book and category entities. To test the service level, the mock-up object approach was used. Testing of the storage layer takes place in test containers to simulate real databases. The controller level is tested using integration tests.
![test-with-coverage](https://github.com/user-attachments/assets/7d2ddcb5-4976-4a0a-8edd-89d103a761b7)

2024-09-10 14:45 UTC, Elena-Bruyako requested changes
see comments

2024-09-10 14:45 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/service/book/impl/BookServiceImpl.java
> +    @Transactional
why did you add this annotation?

2024-09-10 14:45 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/service/book/impl/BookServiceImpl.java
> +    @Transactional
why did you add this annotation?

2024-09-10 14:45 UTC, Elena-Bruyako commented on src/test/java/project/onlinebookstore/controller/BookControllerTest.java
> +        List<BookDto> actualBookDtoList = Arrays.stream(bookDtoResponseArray).toList();
```suggestion
        List<BookDto> actualBookDtoList = objectMapper.readValue(result.getResponse().getContentAsString(),
                new TypeReference<>() {});
```

2024-09-10 14:45 UTC, Elena-Bruyako commented on src/test/java/project/onlinebookstore/controller/BookControllerTest.java
> +        Assertions.assertFalse(actualBookDtoList.isEmpty());
use static imports, check all places

2024-09-10 16:43 UTC, petro2061 commented
Removed Transactional annotation added before. Also removed reduant properties in application.properties file for tests. Added static imports in test classes.

2024-09-11 11:27 UTC, Elena-Bruyako approved these changes

2024-09-12 17:04 UTC, merged