Develop book controller
petro2061/online-book-store-project pull request #2
Opened 2024-06-20 06:33 UTC by petro2061

Added web controller layer for Book model. The DTO approach for obtaining and displaying entity properties has also been implemented. A library was used for this Mapstruct.

2024-06-20 07:04 UTC, Elena-Bruyako requested changes
Good job! Left comments

2024-06-20 07:04 UTC, Elena-Bruyako commented on pom.xml
> +			<version>1.5.5.Final</version>
use properties for mapstruct version here and in plugin section also

2024-06-20 07:04 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/controller/BookController.java
> +@RequestMapping("/api/books")
```suggestion
@RequestMapping("/books")
```

Add `server.servlet.context-path=/api` to application.properties

2024-06-20 07:32 UTC, petro2061 commented
Added new properies to pom.xml file and application.properties. Also fixed request maping annotation.

2024-06-20 08:02 UTC, Elena-Bruyako approved these changes
Well done!

2024-06-26 20:36 UTC, petro2061 commented
Reworked the implementation of the book repository using Spring JPA. Added liquibase to project.

2024-06-27 06:08 UTC, Elena-Bruyako requested changes
Good job! let's fix some comments

2024-06-27 06:08 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/model/Book.java
> +@RequiredArgsConstructor
```suggestion
```

2024-06-27 06:08 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/model/Book.java
> +@Where(clause = "is_deleted = false")
```suggestion
@SQLRestriction(value = "is_deleted = false")
```

`@Where` is deprecated

2024-06-27 06:08 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/model/Book.java
> +    public String toString() {
remove

2024-06-27 06:08 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/service/impl/BookServiceImpl.java
> +        Book bookModelForSave =
```suggestion
        Book book =
```

2024-06-27 06:08 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/service/impl/BookServiceImpl.java
> +        List<Book> allBookFromRepository = bookRepository.findAll();
```suggestion
        return bookRepository.findAll()
                .stream()
                .map(bookMapper::toBookDto)
                .toList();
```

2024-06-27 06:08 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/service/impl/BookServiceImpl.java
> +        bookByIdForUpdate.setId(id);
```suggestion
        bookMapper.updateBookFromDto(bookDto, book);
        return bookMapper.toDto(bookRepository.save(book));
```

2024-06-27 06:08 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/mapper/BookMapper.java
> +    Book toBookModel(CreateBookRequestDto bookRequestDto);
Add
`void updateBookFromDto(CreateBookRequestDto book, @MappingTarget Book entity);`

2024-06-27 17:16 UTC, petro2061 commented
Aded new method for update book entity to mpper class and use it on servise layer. Also fix problem with codestyle.
Do not fix codestyle in BookServiceImpl class because it class is deleted.

2024-06-27 17:28 UTC, petro2061 commented
Added anotation Transactional and fix problem with codestyle

2024-06-29 08:12 UTC, Elena-Bruyako approved these changes
Good job! 
Don't forget to merge approved PRs and implement new HW in branch without previous changes

2024-06-29 08:54 UTC, petro2061 commented
All comments from the mentor have been corrected.

2024-06-29 08:54 UTC, merged