Add validation and ghe
petro2061/online-book-store-project pull request #4
Opened 2024-06-30 16:25 UTC by petro2061

Added valigation package. Packege include custom annotation and implementation for validation input data to server. To pon.xml fille add new dependency and added special annotation on controller methots. Also imlemented CustomExsertionHandler class. This class include methods for handling exceptions at the application level.

2024-07-01 09:15 UTC, Elena-Bruyako requested changes
Let's improve your solution

2024-07-01 09:15 UTC, Elena-Bruyako commented on pom.xml
> +			<groupId>org.hibernate.validator</groupId>
It's better to use spring-boot-starter-validation which provides hibernate-validator also

2024-07-01 09:15 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/dto/CreateBookRequestDto.java
> +    @NotNull(message = "Field title can't be null")
```suggestion
    @NotBlank(message = "Field title can't be null")
```

2024-07-01 09:15 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +    @ExceptionHandler(NullPointerException.class)
remove

2024-07-01 09:15 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/dto/CreateBookRequestDto.java
> +    @NotNull(message = "Field price can't be null")
```suggestion
    @NotBlank(message = "Field price can't be null")
```

2024-07-01 09:15 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +            NullPointerException ex) {
First, why NullPointerException? 
Second, in which places you catching NoSuchElementException?

2024-07-02 06:34 UTC, petro2061 commented
Added another dependency to pom.xml. Changed the annotation from @NotNull to @NotBlank and removed redundant methods.

2024-07-02 06:59 UTC, Elena-Bruyako requested changes
see comments

2024-07-02 06:59 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(getBody(ex), HttpStatus.INTERNAL_SERVER_ERROR);
```suggestion
        return new ResponseEntity<>(getBody(ex), HttpStatus.NOT_FOUND);
```

2024-07-02 06:59 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +    @ExceptionHandler(DataProcessingException.class)
Did you use this exception? 
If so, please fix the HttpStatus

2024-07-02 07:29 UTC, petro2061 commented
Changed HttpStatus and deleted not use handler

2024-07-02 16:35 UTC, Elena-Bruyako approved these changes
Good job!

2024-07-02 16:36 UTC, Elena-Bruyako commented
Rejected my mistake on the platform. Could you please send PR again?

2024-07-03 07:13 UTC, merged