Add pagination sorting swagger
petro2061/online-book-store-project pull request #5
Opened 2024-07-03 07:37 UTC by petro2061

Added Pageable object to findAll method in Boot Controller class. Methods in the BookController class are also described, using the Open Api annotation.

2024-07-03 08:55 UTC, Elena-Bruyako requested changes
Good job! Let's improve it

2024-07-03 08:55 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/config/OpenApiConfig.java
> +
```suggestion
```

2024-07-03 08:55 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/controller/BookController.java
> +            Pageable pageable) {
```suggestion
            @ParameterObject @PageableDefault Pageable pageable) {
```

2024-07-03 08:55 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/controller/BookController.java
> +            @PathVariable Long id) {
```suggestion
            @PathVariable @Positive Long id) {
```

2024-07-03 08:55 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/controller/BookController.java
> +            @PathVariable Long id) {
```suggestion
            @PathVariable @Positive Long id) {
```

2024-07-03 08:55 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/controller/BookController.java
> +            @PathVariable Long id,
```suggestion
            @PathVariable @Positive Long id,
```

2024-07-03 08:55 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/controller/BookController.java
> +            BookSearchParameters searchParameters) {
```suggestion
            BookSearchParameters searchParameters, @ParameterObject @PageableDefault Pageable pageable) {
```

2024-07-03 08:55 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/controller/BookController.java
>          return bookService.searchBooks(searchParameters);
```suggestion
        return bookService.searchBooks(searchParameters, pageable);
```

2024-07-03 08:55 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/controller/BookController.java
>  @RequestMapping("/books")
```suggestion
@RequestMapping("/books")
@Validated
```

2024-07-03 10:35 UTC, petro2061 commented
fix problem with codestyle and added new annotation to BookController class. In CreateBookRequestDto class changed annotation NotBlant to NotNull becouse i recived error: "No validator could be found for constraint 'jakarta.validation.constraints.NotBlank' validating type 'java.math.BigDecimal'. Check configuration for 'price'"

2024-07-04 06:36 UTC, Elena-Bruyako requested changes
see the comment

2024-07-04 06:36 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/controller/BookController.java
> +            @PathVariable Long id,
not fixed

2024-07-04 07:58 UTC, petro2061 commented
Added annotation @Positive to field Long id.

2024-07-05 12:40 UTC, Elena-Bruyako approved these changes
Good job

2024-07-06 06:49 UTC, merged