SBS add spring security
petro2061/online-book-store-project pull request #7
Opened 2024-07-18 23:14 UTC by petro2061

Adde Spring Security to project. Implemented SecurityConfig class and CustomUserDetailsService that implements UserDetailsService. Updated user model. An implementation of the UserDetails interfase was added to the model and added new fild roles. Created new model Role that represented access to endpoints for roles. Фnd changed book controller - added roles to endpoints.

2024-07-19 07:07 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution

2024-07-19 07:07 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/config/SecurityConfig.java
> +
```suggestion
```

2024-07-19 07:07 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/model/Role.java
> +@Entity
entity should has get and set methods

2024-07-19 07:07 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/model/Role.java
> +        USER,
```suggestion
        ROLE_USER,
        ROLE_ADMIN
```

2024-07-19 07:07 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/controller/BookController.java
> +    @PreAuthorize("hasRole('ROLE_USER')")
You can avoid using prefix, Spring Security adds it automatically

2024-07-19 07:07 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/security/CustomUserDetailsService.java
> +            throws UsernameNotFoundException {
```suggestion
```

2024-07-19 07:07 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/security/CustomUserDetailsService.java
> +                () -> new UsernameNotFoundException("Can't find user with email: "
```suggestion
                () -> new EntityNotFoundException("Can't find user with email: "
```

2024-07-19 07:07 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/service/user/impl/UserServiceImpl.java
> +        User savedUserModel = userMapper.toUserModel(registrationRequestDto);
```suggestion
        User user = userMapper.toUserModel(registrationRequestDto);
```

2024-07-19 07:07 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/06-insert-admin_user-to-users.yaml
> +                          value: "$2y$10$pCqsETLdAj6d4QvuhPlbDuX4o5HWu98Y8wLs58bRVJ.e2u4IlUXBG"} # "admin_12345!" hashed with BCrypt
remove comment

2024-07-19 09:15 UTC, petro2061 commented
Deleted prefix 'ROLE_' in BookController. Changed naming roles. Added EntityNotFoundException in CustomUserDetailsService.

2024-07-20 10:56 UTC, Elena-Bruyako requested changes
Good job! Let's improve it

2024-07-20 10:56 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/config/SecurityConfig.java
> +@EnableMethodSecurity
Do you need both of this annotations `@EnableWebSecurity and @EnableMethodSecurity`?

2024-07-20 10:56 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/security/CustomUserDetailsService.java
> +            throws EntityNotFoundException {
```suggestion
```

2024-07-20 10:56 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/service/user/impl/UserServiceImpl.java
> +                        new EntityNotFoundException("Can't find role: USER"));
Use Role.RoleName.ROLE_USER in message

2024-07-20 10:56 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/service/user/impl/UserServiceImpl.java
> +        user.getRoles().add(userRole);
```suggestion
        user.setRoles(Set.of(userRole));
```

2024-07-20 12:10 UTC, petro2061 commented
Fixed config class and register() method in UserServise class

2024-07-20 16:37 UTC, Sanderfuck requested changes

2024-07-20 16:37 UTC, Sanderfuck commented on src/main/java/project/onlinebookstore/service/user/impl/UserServiceImpl.java
> +                = roleRepository
```suggestion
        Role userRole = roleRepository
```

2024-07-20 22:13 UTC, petro2061 commented
fixsed problem with codestyle and PreAuthorize annotation

2024-07-21 08:10 UTC, Elena-Bruyako approved these changes

2024-07-21 08:45 UTC, merged