SBS add jwt support
petro2061/online-book-store-project pull request #8
Opened 2024-07-21 09:26 UTC by petro2061

Added new clasees: JwtUtil - incude methods for generat JWT token and that validation, JwtAuthenticationFilter - implemented custom filter that checked corect authentication users bases on JWT token, AuthenticationService - implemented logic for authentication users. Also added swagger security and corresponding annotations. Also added necessary changes to configuration files, classes for implementing stateless applications.

2024-07-21 15:13 UTC, MentorMateAcademy requested changes

2024-07-21 15:13 UTC, MentorMateAcademy commented on src/main/java/project/onlinebookstore/config/OpenApiConfig.java
> +                .addSecurityItem(new SecurityRequirement().addList("BearerAuth"));
strings can save to constants

2024-07-21 20:28 UTC, petro2061 commented
Added constsnts and lose anntations

2024-07-22 14:04 UTC, Elena-Bruyako requested changes
see comments

2024-07-22 14:04 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/config/OpenApiConfig.java
> +    private static final String SCHEMA_TYPE = "bearer";
why do you need two similar constant?

2024-07-22 14:04 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/config/OpenApiConfig.java
> +    private static final String SECURITY_ITEM_LIST_NAME = "BearerAuth";
```suggestion
    private static final String SECURITY_SCHEME_NAME = "BearerAuth";
```

2024-07-22 14:04 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +    public ResponseEntity<Map<String, Object>> handleJwtException(
check this, GlogalExceptionHandler doesn't handle exceptions from filters

2024-07-22 14:04 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/security/JwtAuthenticationFilter.java
> +    private static final int START_TOKEN_INDEX = 7;
```suggestion
    private static final String TOKEN_HEADER = "Bearer ";
```

2024-07-22 14:04 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/security/JwtAuthenticationFilter.java
> +            return barerToken.substring(START_TOKEN_INDEX);
```suggestion
            return barerToken.substring(TOKEN_HEADER.length());
```

2024-07-22 14:04 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/security/JwtAuthenticationFilter.java
> +        String barerToken = request.getHeader(HEADER_NAME);
```suggestion
        String barerToken = request.getHeader(HttpHeaders.AUTHORIZATION);
```

use Spring constant

2024-07-22 21:00 UTC, petro2061 commented
Mentor comments corrected. Deleted exseption handlers in GlobalExseptionHandler.

2024-07-23 08:53 UTC, Elena-Bruyako requested changes
Good job. Just one comment

2024-07-23 08:53 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/config/OpenApiConfig.java
> +                .components(new Components().addSecuritySchemes("BearerAuth",
```suggestion
                .components(new Components().addSecuritySchemes(SECURITY_SCHEMA_NAME,
```

2024-07-23 16:54 UTC, petro2061 commented
added lose annotation to OpenApi config

2024-07-24 12:50 UTC, Elena-Bruyako approved these changes

2024-07-24 15:37 UTC, merged