SBP add category model
petro2061/online-book-store-project pull request #9
Opened 2024-07-24 16:49 UTC by petro2061

Implemented a new controller containing category management endpoints. The entity of the category represents a certain type to which many books can belong. Therefore, a category field marked with an annotation @ManytoMany is added to the book entity. Also to project added category repository and category servise that include method for delete, save and update mathod for management category entity. To book reposetory and servise added method for find book by category id. Also implemented Category mapper class and modifired book mapper class. To mathod that search books by params adde new provider for serch by category id and modifired another providers for avoid lazy initialsation exseption.

2024-07-25 19:21 UTC, Elena-Bruyako requested changes
Just one comment

2024-07-25 19:21 UTC, Elena-Bruyako commented on src/main/java/project/onlinebookstore/dto/book/CreateBookRequestDto.java
> +    @NotNull(message = "Can be empty but not null")
```suggestion
    @NotEmpty(message = "Can be empty but not null")
```

2024-07-25 21:09 UTC, petro2061 commented
Changed annotation NotNull to NotEmpty

2024-07-26 10:51 UTC, Elena-Bruyako approved these changes
well done

2024-07-26 15:58 UTC, merged